require 'erp_app/widgets/base'
require 'erp_app/widgets/loader'
require 'erp_app/widgets/javascript_loader'
require 'erp_app/widgets/helpers/widget_helper'
require 'erp_app/widgets/railties/action_view'