source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '~> 1.3.4'
gem 'jquery-rails', '1.0.13'

# Compass AE engines
gem 'erp_commerce', :path => '../erp_commerce'

group :development, :test do
  gem 'rspec-rails', '2.5'
end



