source "http://rubygems.org"

gem 'rails', '3.1.0.rc5'
gem "arel", "2.1.4"

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

group :development, :test do
  gem 'rspec-rails', '~> 2.5'
end

gem 'jquery-rails'
# To use debugger
# gem 'ruby-debug'

gem 'data_migrator'
gem 'has_many_polymorphic'
gem 'will_paginate', '~> 3.0.pre4'
gem 'attr_encrypted'
gem 'awesome_nested_set'