source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '1.3.4'
gem 'jquery-rails', '1.0.13'
gem 'data_migrator', '1.7'
gem 'has_many_polymorphic', '0.5.0'
gem 'attr_encrypted', '1.2.0'
gem 'awesome_nested_set', '2.0.2'
gem "uuid", "2.3.4"

group :development, :test do
  gem 'rspec-rails', '2.5'
end