source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '1.3.4'
gem 'jquery-rails', '1.0.13'
gem 'data_migrator', '1.7'
gem 'has_many_polymorphic', '0.5.0'
gem 'attr_encrypted', '1.2.0'
gem 'awesome_nested_set', '2.0.2'
gem "uuid", "2.3.4"

group :development, :test do
  gem 'cucumber-rails', "~> 1.1.1"
  gem 'database_cleaner'
  gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
  gem 'factory_girl_rails', '1.2.0'
  gem 'rspec-rails', '~> 2.7'
  gem 'watchr'
  gem 'spork', '~> 0.9.0.rc'
  gem 'simplecov', '>= 0.5.4'
end
