source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '1.3.4'
gem 'jquery-rails', '1.0.13'
gem "devise", "~> 1.4.8"
gem 'paperclip', '2.4.5'
gem 'delayed_job', '2.1.4'
gem 'aws-s3', '0.6.2'

# Compass AE engines
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'

group :development, :test do
  gem 'cucumber-rails', "~> 1.1.1"
  gem 'database_cleaner'
  gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
  gem 'factory_girl_rails', '1.2.0'
  gem 'rspec-rails', '~> 2.7'
  gem 'watchr'
  gem 'spork', '~> 0.9.0.rc'
  gem 'simplecov', '>= 0.5.4'
end
