source "http://rubygems.org"

gem 'rails', '3.1.0.rc5'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'jquery-rails'
# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development, :test do
  gem 'rspec-rails', '~> 2.5'
end

gem 'devise', '1.1.rc0'
gem 'paperclip'
gem 'delayed_job'
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
