source "http://rubygems.org"

gem 'rails', '3.1.0.rc5'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'jquery-rails'
# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'paperclip'
#gem "acts_as_versioned", :path => 'vendor/plugins/acts_as_versioned'
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'