source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '~> 1.3.4'
gem 'jquery-rails', '1.0.13'
gem 'will_paginate', '3.0.0'

# Compass AE engines
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'
gem 'erp_app', :path => '../erp_app'
gem 'erp_agreements', :path => '../erp_agreements'
gem 'erp_commerce', :path => '../erp_commerce'
gem 'erp_products', :path => '../erp_products'
gem 'erp_orders', :path => '../erp_orders'

group :development, :test do
  gem 'cucumber-rails', "~> 1.1.1"
  gem 'database_cleaner'
  gem 'factory_girl_rails', '1.2.0'
  gem 'rspec-rails', '~> 2.7'
  gem 'watchr'
  gem 'spork', '~> 0.9.0.rc'
  gem 'simplecov', '>= 0.5.4'
end



