source 'http://rubygems.org'

gem 'rails', '3.1.1.rc1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

gem 'erp_base_erp_svcs', :path => '../compass_agile_enterprise/erp_base_erp_svcs'
gem 'erp_dev_svcs', :path => '../compass_agile_enterprise/erp_dev_svcs'
gem 'erp_tech_svcs', :path => '../compass_agile_enterprise/erp_tech_svcs'
gem 'erp_app', :path => '../compass_agile_enterprise/erp_app'
gem 'erp_forms', :path => '../compass_agile_enterprise/erp_forms'
gem 'knitkit', :path => '../compass_agile_enterprise/knitkit'
gem 'rails_db_admin', :path => '../compass_agile_enterprise/rails_db_admin'
gem 'console', :path => '../compass_agile_enterprise/console'
