source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3'

gem 'jquery-rails'
# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development, :test do
  gem 'rspec-rails', '~> 2.5'
end

gem 'routing-filter'
gem 'nokogiri'
gem 'rubyzip'
gem 'permalink_fu'
gem 'acts-as-taggable-on'
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'
gem 'erp_app', :path => '../erp_app'
gem 'erp_forms', :path => '../erp_forms'