source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '1.3.4'
gem 'jquery-rails', '1.0.13'
gem 'routing-filter', '0.2.4'
gem 'nokogiri', '1.5.0'
gem 'rubyzip', '0.9.4'
gem 'permalink_fu', '1.0.0'
gem 'acts-as-taggable-on', '2.1.1'

#Compass AE engines
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'
gem 'erp_app', :path => '../erp_app'
gem 'erp_forms', :path => '../erp_forms'

group :development, :test do
  gem 'rspec-rails', '2.5'
end