class CreateCountries < ActiveRecord::Migration
  def self.up
    create_table :geo_countries do |t|
      t.column :name, :string
      t.column :type, :string, :default => "GeoCountry"
      t.column :iso_code_2, :string, :length => 2
      t.column :iso_code_3, :string, :length => 3
      t.column :display, :boolean, :default => true
      t.column :external_id, :integer
      t.column :created_at, :datetime
    end

    GeoCountry.create(:name => 'Afghanistan', :iso_code_2 => 'AF', :iso_code_3 => 'AFG', :display => true)
    GeoCountry.create(:name => 'Albania', :iso_code_2 => 'AL', :iso_code_3 => 'ALB', :display => true)
    GeoCountry.create(:name => 'Algeria', :iso_code_2 => 'DZ', :iso_code_3 => 'DZA', :display => true)
    GeoCountry.create(:name => 'American Samoa', :iso_code_2 => 'AS', :iso_code_3 => 'ASM', :display => true)
    GeoCountry.create(:name => 'Andorra', :iso_code_2 => 'AD', :iso_code_3 => 'AND', :display => true)
    GeoCountry.create(:name => 'Angola', :iso_code_2 => 'AO', :iso_code_3 => 'AGO', :display => true)
    GeoCountry.create(:name => 'Anguilla', :iso_code_2 => 'AI', :iso_code_3 => 'AIA', :display => true)
    GeoCountry.create(:name => 'Antarctica', :iso_code_2 => 'AQ', :iso_code_3 => 'ATA', :display => true)
    GeoCountry.create(:name => 'Antigua and Barbuda', :iso_code_2 => 'AG', :iso_code_3 => 'ATG', :display => true)
    GeoCountry.create(:name => 'Argentina', :iso_code_2 => 'AR', :iso_code_3 => 'ARG', :display => true)
    GeoCountry.create(:name => 'Armenia', :iso_code_2 => 'AM', :iso_code_3 => 'ARM', :display => true)
    GeoCountry.create(:name => 'Aruba', :iso_code_2 => 'AW', :iso_code_3 => 'ABW', :display => true)
    GeoCountry.create(:name => 'Australia', :iso_code_2 => 'AU', :iso_code_3 => 'AUS', :display => true)
    GeoCountry.create(:name => 'Austria', :iso_code_2 => 'AT', :iso_code_3 => 'AUT', :display => true)
    GeoCountry.create(:name => 'Azerbaijan', :iso_code_2 => 'AZ', :iso_code_3 => 'AZE', :display => true)
    GeoCountry.create(:name => 'Bahamas', :iso_code_2 => 'BS', :iso_code_3 => 'BHS', :display => true)
    GeoCountry.create(:name => 'Bahrain', :iso_code_2 => 'BH', :iso_code_3 => 'BHR', :display => true)
    GeoCountry.create(:name => 'Bangladesh', :iso_code_2 => 'BD', :iso_code_3 => 'BGD', :display => true)
    GeoCountry.create(:name => 'Barbados', :iso_code_2 => 'BB', :iso_code_3 => 'BRB', :display => true)
    GeoCountry.create(:name => 'Belarus', :iso_code_2 => 'BY', :iso_code_3 => 'BLR', :display => true)
    GeoCountry.create(:name => 'Belgium', :iso_code_2 => 'BE', :iso_code_3 => 'BEL', :display => true)
    GeoCountry.create(:name => 'Belize', :iso_code_2 => 'BZ', :iso_code_3 => 'BLZ', :display => true)
    GeoCountry.create(:name => 'Benin', :iso_code_2 => 'BJ', :iso_code_3 => 'BEN', :display => true)
    GeoCountry.create(:name => 'Bermuda', :iso_code_2 => 'BM', :iso_code_3 => 'BMU', :display => true)
    GeoCountry.create(:name => 'Bhutan', :iso_code_2 => 'BT', :iso_code_3 => 'BTN', :display => true)
    GeoCountry.create(:name => 'Bolivia', :iso_code_2 => 'BO', :iso_code_3 => 'BOL', :display => true)
    GeoCountry.create(:name => 'Bosnia and Herzegowina', :iso_code_2 => 'BA', :iso_code_3 => 'BIH', :display => true)
    GeoCountry.create(:name => 'Botswana', :iso_code_2 => 'BW', :iso_code_3 => 'BWA', :display => true)
    GeoCountry.create(:name => 'Bouvet Island', :iso_code_2 => 'BV', :iso_code_3 => 'BVT', :display => true)
    GeoCountry.create(:name => 'Brazil', :iso_code_2 => 'BR', :iso_code_3 => 'BRA', :display => true)
    GeoCountry.create(:name => 'British Indian Ocean Territory', :iso_code_2 => 'IO', :iso_code_3 => 'IOT', :display => true)
    GeoCountry.create(:name => 'Brunei Darussalam', :iso_code_2 => 'BN', :iso_code_3 => 'BRN', :display => true)
    GeoCountry.create(:name => 'Bulgaria', :iso_code_2 => 'BG', :iso_code_3 => 'BGR', :display => true)
    GeoCountry.create(:name => 'Burkina Faso', :iso_code_2 => 'BF', :iso_code_3 => 'BFA', :display => true)
    GeoCountry.create(:name => 'Burundi', :iso_code_2 => 'BI', :iso_code_3 => 'BDI', :display => true)
    GeoCountry.create(:name => 'Cambodia', :iso_code_2 => 'KH', :iso_code_3 => 'KHM', :display => true)
    GeoCountry.create(:name => 'Cameroon', :iso_code_2 => 'CM', :iso_code_3 => 'CMR', :display => true)
    GeoCountry.create(:name => 'Canada', :iso_code_2 => 'CA', :iso_code_3 => 'CAN', :display => true)
    GeoCountry.create(:name => 'Cape Verde', :iso_code_2 => 'CV', :iso_code_3 => 'CPV', :display => true)
    GeoCountry.create(:name => 'Cayman Islands', :iso_code_2 => 'KY', :iso_code_3 => 'CYM', :display => true)
    GeoCountry.create(:name => 'Central African Republic', :iso_code_2 => 'CF', :iso_code_3 => 'CAF', :display => true)
    GeoCountry.create(:name => 'Chad', :iso_code_2 => 'TD', :iso_code_3 => 'TCD', :display => true)
    GeoCountry.create(:name => 'Chile', :iso_code_2 => 'CL', :iso_code_3 => 'CHL', :display => true)
    GeoCountry.create(:name => 'China', :iso_code_2 => 'CN', :iso_code_3 => 'CHN', :display => true)
    GeoCountry.create(:name => 'Christmas Island', :iso_code_2 => 'CX', :iso_code_3 => 'CXR', :display => true)
    GeoCountry.create(:name => 'Cocos (Keeling) Islands', :iso_code_2 => 'CC', :iso_code_3 => 'CCK', :display => true)
    GeoCountry.create(:name => 'Colombia', :iso_code_2 => 'CO', :iso_code_3 => 'COL', :display => true)
    GeoCountry.create(:name => 'Comoros', :iso_code_2 => 'KM', :iso_code_3 => 'COM', :display => true)
    GeoCountry.create(:name => 'Congo', :iso_code_2 => 'CG', :iso_code_3 => 'COG', :display => true)
    GeoCountry.create(:name => 'Cook Islands', :iso_code_2 => 'CK', :iso_code_3 => 'COK', :display => true)
    GeoCountry.create(:name => 'Costa Rica', :iso_code_2 => 'CR', :iso_code_3 => 'CRI', :display => true)
    GeoCountry.create(:name => 'Cote D''Ivoire', :iso_code_2 => 'CI', :iso_code_3 => 'CIV', :display => true)
    GeoCountry.create(:name => 'Croatia', :iso_code_2 => 'HR', :iso_code_3 => 'HRV', :display => true)
    GeoCountry.create(:name => 'Cuba', :iso_code_2 => 'CU', :iso_code_3 => 'CUB', :display => true)
    GeoCountry.create(:name => 'Cyprus', :iso_code_2 => 'CY', :iso_code_3 => 'CYP', :display => true)
    GeoCountry.create(:name => 'Czech Republic', :iso_code_2 => 'CZ', :iso_code_3 => 'CZE', :display => true)
    GeoCountry.create(:name => 'Denmark', :iso_code_2 => 'DK', :iso_code_3 => 'DNK', :display => true)
    GeoCountry.create(:name => 'Djibouti', :iso_code_2 => 'DJ', :iso_code_3 => 'DJI', :display => true)
    GeoCountry.create(:name => 'Dominica', :iso_code_2 => 'DM', :iso_code_3 => 'DMA', :display => true)
    GeoCountry.create(:name => 'Dominican Republic', :iso_code_2 => 'DO', :iso_code_3 => 'DOM', :display => true)
    GeoCountry.create(:name => 'East Timor', :iso_code_2 => 'TP', :iso_code_3 => 'TMP', :display => true)
    GeoCountry.create(:name => 'Ecuador', :iso_code_2 => 'EC', :iso_code_3 => 'ECU', :display => true)
    GeoCountry.create(:name => 'Egypt', :iso_code_2 => 'EG', :iso_code_3 => 'EGY', :display => true)
    GeoCountry.create(:name => 'El Salvador', :iso_code_2 => 'SV', :iso_code_3 => 'SLV', :display => true)
    GeoCountry.create(:name => 'Equatorial Guinea', :iso_code_2 => 'GQ', :iso_code_3 => 'GNQ', :display => true)
    GeoCountry.create(:name => 'Eritrea', :iso_code_2 => 'ER', :iso_code_3 => 'ERI', :display => true)
    GeoCountry.create(:name => 'Estonia', :iso_code_2 => 'EE', :iso_code_3 => 'EST', :display => true)
    GeoCountry.create(:name => 'Ethiopia', :iso_code_2 => 'ET', :iso_code_3 => 'ETH', :display => true)
    GeoCountry.create(:name => 'Falkland Islands (Malvinas)', :iso_code_2 => 'FK', :iso_code_3 => 'FLK', :display => true)
    GeoCountry.create(:name => 'Faroe Islands', :iso_code_2 => 'FO', :iso_code_3 => 'FRO', :display => true)
    GeoCountry.create(:name => 'Fiji', :iso_code_2 => 'FJ', :iso_code_3 => 'FJI', :display => true)
    GeoCountry.create(:name => 'Finland', :iso_code_2 => 'FI', :iso_code_3 => 'FIN', :display => true)
    GeoCountry.create(:name => 'France', :iso_code_2 => 'FR', :iso_code_3 => 'FRA', :display => true)
    GeoCountry.create(:name => 'France, Metropolitan', :iso_code_2 => 'FX', :iso_code_3 => 'FXX', :display => true)
    GeoCountry.create(:name => 'French Guiana', :iso_code_2 => 'GF', :iso_code_3 => 'GUF', :display => true)
    GeoCountry.create(:name => 'French Polynesia', :iso_code_2 => 'PF', :iso_code_3 => 'PYF', :display => true)
    GeoCountry.create(:name => 'French Southern Territories', :iso_code_2 => 'TF', :iso_code_3 => 'ATF', :display => true)
    GeoCountry.create(:name => 'Gabon', :iso_code_2 => 'GA', :iso_code_3 => 'GAB', :display => true)
    GeoCountry.create(:name => 'Gambia', :iso_code_2 => 'GM', :iso_code_3 => 'GMB', :display => true)
    GeoCountry.create(:name => 'Georgia', :iso_code_2 => 'GE', :iso_code_3 => 'GEO', :display => true)
    GeoCountry.create(:name => 'Germany', :iso_code_2 => 'DE', :iso_code_3 => 'DEU', :display => true)
    GeoCountry.create(:name => 'Ghana', :iso_code_2 => 'GH', :iso_code_3 => 'GHA', :display => true)
    GeoCountry.create(:name => 'Gibraltar', :iso_code_2 => 'GI', :iso_code_3 => 'GIB', :display => true)
    GeoCountry.create(:name => 'Greece', :iso_code_2 => 'GR', :iso_code_3 => 'GRC', :display => true)
    GeoCountry.create(:name => 'Greenland', :iso_code_2 => 'GL', :iso_code_3 => 'GRL', :display => true)
    GeoCountry.create(:name => 'Grenada', :iso_code_2 => 'GD', :iso_code_3 => 'GRD', :display => true)
    GeoCountry.create(:name => 'Guadeloupe', :iso_code_2 => 'GP', :iso_code_3 => 'GLP', :display => true)
    GeoCountry.create(:name => 'Guam', :iso_code_2 => 'GU', :iso_code_3 => 'GUM', :display => true)
    GeoCountry.create(:name => 'Guatemala', :iso_code_2 => 'GT', :iso_code_3 => 'GTM', :display => true)
    GeoCountry.create(:name => 'Guinea', :iso_code_2 => 'GN', :iso_code_3 => 'GIN', :display => true)
    GeoCountry.create(:name => 'Guinea-bissau', :iso_code_2 => 'GW', :iso_code_3 => 'GNB', :display => true)
    GeoCountry.create(:name => 'Guyana', :iso_code_2 => 'GY', :iso_code_3 => 'GUY', :display => true)
    GeoCountry.create(:name => 'Haiti', :iso_code_2 => 'HT', :iso_code_3 => 'HTI', :display => true)
    GeoCountry.create(:name => 'Heard and Mc Donald Islands', :iso_code_2 => 'HM', :iso_code_3 => 'HMD', :display => true)
    GeoCountry.create(:name => 'Honduras', :iso_code_2 => 'HN', :iso_code_3 => 'HND', :display => true)
    GeoCountry.create(:name => 'Hong Kong', :iso_code_2 => 'HK', :iso_code_3 => 'HKG', :display => true)
    GeoCountry.create(:name => 'Hungary', :iso_code_2 => 'HU', :iso_code_3 => 'HUN', :display => true)
    GeoCountry.create(:name => 'Iceland', :iso_code_2 => 'IS', :iso_code_3 => 'ISL', :display => true)
    GeoCountry.create(:name => 'India', :iso_code_2 => 'IN', :iso_code_3 => 'IND', :display => true)
    GeoCountry.create(:name => 'Indonesia', :iso_code_2 => 'ID', :iso_code_3 => 'IDN', :display => true)
    GeoCountry.create(:name => 'Iran (Islamic Republic of)', :iso_code_2 => 'IR', :iso_code_3 => 'IRN', :display => true)
    GeoCountry.create(:name => 'Iraq', :iso_code_2 => 'IQ', :iso_code_3 => 'IRQ', :display => true)
    GeoCountry.create(:name => 'Ireland', :iso_code_2 => 'IE', :iso_code_3 => 'IRL', :display => true)
    GeoCountry.create(:name => 'Israel', :iso_code_2 => 'IL', :iso_code_3 => 'ISR', :display => true)
    GeoCountry.create(:name => 'Italy', :iso_code_2 => 'IT', :iso_code_3 => 'ITA', :display => true)
    GeoCountry.create(:name => 'Jamaica', :iso_code_2 => 'JM', :iso_code_3 => 'JAM', :display => true)
    GeoCountry.create(:name => 'Japan', :iso_code_2 => 'JP', :iso_code_3 => 'JPN', :display => true)
    GeoCountry.create(:name => 'Jordan', :iso_code_2 => 'JO', :iso_code_3 => 'JOR', :display => true)
    GeoCountry.create(:name => 'Kazakhstan', :iso_code_2 => 'KZ', :iso_code_3 => 'KAZ', :display => true)
    GeoCountry.create(:name => 'Kenya', :iso_code_2 => 'KE', :iso_code_3 => 'KEN', :display => true)
    GeoCountry.create(:name => 'Kiribati', :iso_code_2 => 'KI', :iso_code_3 => 'KIR', :display => true)
    GeoCountry.create(:name => "Korea, Democratic People's Republic of", :iso_code_2 => 'KP', :iso_code_3 => 'PRK', :display => true)
    GeoCountry.create(:name => 'Korea, Republic of', :iso_code_2 => 'KR', :iso_code_3 => 'KOR', :display => true)
    GeoCountry.create(:name => 'Kuwait', :iso_code_2 => 'KW', :iso_code_3 => 'KWT', :display => true)
    GeoCountry.create(:name => 'Kyrgyzstan', :iso_code_2 => 'KG', :iso_code_3 => 'KGZ', :display => true)
    GeoCountry.create(:name => 'Lao People''s Democratic Republic', :iso_code_2 => 'LA', :iso_code_3 => 'LAO', :display => true)
    GeoCountry.create(:name => 'Latvia', :iso_code_2 => 'LV', :iso_code_3 => 'LVA', :display => true)
    GeoCountry.create(:name => 'Lebanon', :iso_code_2 => 'LB', :iso_code_3 => 'LBN', :display => true)
    GeoCountry.create(:name => 'Lesotho', :iso_code_2 => 'LS', :iso_code_3 => 'LSO', :display => true)
    GeoCountry.create(:name => 'Liberia', :iso_code_2 => 'LR', :iso_code_3 => 'LBR', :display => true)
    GeoCountry.create(:name => 'Libyan Arab Jamahiriya', :iso_code_2 => 'LY', :iso_code_3 => 'LBY', :display => true)
    GeoCountry.create(:name => 'Liechtenstein', :iso_code_2 => 'LI', :iso_code_3 => 'LIE', :display => true)
    GeoCountry.create(:name => 'Lithuania', :iso_code_2 => 'LT', :iso_code_3 => 'LTU', :display => true)
    GeoCountry.create(:name => 'Luxembourg', :iso_code_2 => 'LU', :iso_code_3 => 'LUX', :display => true)
    GeoCountry.create(:name => 'Macau', :iso_code_2 => 'MO', :iso_code_3 => 'MAC', :display => true)
    GeoCountry.create(:name => 'Macedonia, The Former Yugoslav Republic of', :iso_code_2 => 'MK', :iso_code_3 => 'MKD', :display => true)
    GeoCountry.create(:name => 'Madagascar', :iso_code_2 => 'MG', :iso_code_3 => 'MDG', :display => true)
    GeoCountry.create(:name => 'Malawi', :iso_code_2 => 'MW', :iso_code_3 => 'MWI', :display => true)
    GeoCountry.create(:name => 'Malaysia', :iso_code_2 => 'MY', :iso_code_3 => 'MYS', :display => true)
    GeoCountry.create(:name => 'Maldives', :iso_code_2 => 'MV', :iso_code_3 => 'MDV', :display => true)
    GeoCountry.create(:name => 'Mali', :iso_code_2 => 'ML', :iso_code_3 => 'MLI', :display => true)
    GeoCountry.create(:name => 'Malta', :iso_code_2 => 'MT', :iso_code_3 => 'MLT', :display => true)
    GeoCountry.create(:name => 'Marshall Islands', :iso_code_2 => 'MH', :iso_code_3 => 'MHL', :display => true)
    GeoCountry.create(:name => 'Martinique', :iso_code_2 => 'MQ', :iso_code_3 => 'MTQ', :display => true)
    GeoCountry.create(:name => 'Mauritania', :iso_code_2 => 'MR', :iso_code_3 => 'MRT', :display => true)
    GeoCountry.create(:name => 'Mauritius', :iso_code_2 => 'MU', :iso_code_3 => 'MUS', :display => true)
    GeoCountry.create(:name => 'Mayotte', :iso_code_2 => 'YT', :iso_code_3 => 'MYT', :display => true)
    GeoCountry.create(:name => 'Mexico', :iso_code_2 => 'MX', :iso_code_3 => 'MEX', :display => true)
    GeoCountry.create(:name => 'Micronesia, Federated States of', :iso_code_2 => 'FM', :iso_code_3 => 'FSM', :display => true)
    GeoCountry.create(:name => 'Moldova, Republic of', :iso_code_2 => 'MD', :iso_code_3 => 'MDA', :display => true)
    GeoCountry.create(:name => 'Monaco', :iso_code_2 => 'MC', :iso_code_3 => 'MCO', :display => true)
    GeoCountry.create(:name => 'Mongolia', :iso_code_2 => 'MN', :iso_code_3 => 'MNG', :display => true)
    GeoCountry.create(:name => 'Montserrat', :iso_code_2 => 'MS', :iso_code_3 => 'MSR', :display => true)
    GeoCountry.create(:name => 'Morocco', :iso_code_2 => 'MA', :iso_code_3 => 'MAR', :display => true)
    GeoCountry.create(:name => 'Mozambique', :iso_code_2 => 'MZ', :iso_code_3 => 'MOZ', :display => true)
    GeoCountry.create(:name => 'Myanmar', :iso_code_2 => 'MM', :iso_code_3 => 'MMR', :display => true)
    GeoCountry.create(:name => 'Namibia', :iso_code_2 => 'NA', :iso_code_3 => 'NAM', :display => true)
    GeoCountry.create(:name => 'Nauru', :iso_code_2 => 'NR', :iso_code_3 => 'NRU', :display => true)
    GeoCountry.create(:name => 'Nepal', :iso_code_2 => 'NP', :iso_code_3 => 'NPL', :display => true)
    GeoCountry.create(:name => 'Netherlands', :iso_code_2 => 'NL', :iso_code_3 => 'NLD', :display => true)
    GeoCountry.create(:name => 'Netherlands Antilles', :iso_code_2 => 'AN', :iso_code_3 => 'ANT', :display => true)
    GeoCountry.create(:name => 'New Caledonia', :iso_code_2 => 'NC', :iso_code_3 => 'NCL', :display => true)
    GeoCountry.create(:name => 'New Zealand', :iso_code_2 => 'NZ', :iso_code_3 => 'NZL', :display => true)
    GeoCountry.create(:name => 'Nicaragua', :iso_code_2 => 'NI', :iso_code_3 => 'NIC', :display => true)
    GeoCountry.create(:name => 'Niger', :iso_code_2 => 'NE', :iso_code_3 => 'NER', :display => true)
    GeoCountry.create(:name => 'Nigeria', :iso_code_2 => 'NG', :iso_code_3 => 'NGA', :display => true)
    GeoCountry.create(:name => 'Niue', :iso_code_2 => 'NU', :iso_code_3 => 'NIU', :display => true)
    GeoCountry.create(:name => 'Norfolk Island', :iso_code_2 => 'NF', :iso_code_3 => 'NFK', :display => true)
    GeoCountry.create(:name => 'Northern Mariana Islands', :iso_code_2 => 'MP', :iso_code_3 => 'MNP', :display => true)
    GeoCountry.create(:name => 'Norway', :iso_code_2 => 'NO', :iso_code_3 => 'NOR', :display => true)
    GeoCountry.create(:name => 'Oman', :iso_code_2 => 'OM', :iso_code_3 => 'OMN', :display => true)
    GeoCountry.create(:name => 'Pakistan', :iso_code_2 => 'PK', :iso_code_3 => 'PAK', :display => true)
    GeoCountry.create(:name => 'Palau', :iso_code_2 => 'PW', :iso_code_3 => 'PLW', :display => true)
    GeoCountry.create(:name => 'Panama', :iso_code_2 => 'PA', :iso_code_3 => 'PAN', :display => true)
    GeoCountry.create(:name => 'Papua New Guinea', :iso_code_2 => 'PG', :iso_code_3 => 'PNG', :display => true)
    GeoCountry.create(:name => 'Paraguay', :iso_code_2 => 'PY', :iso_code_3 => 'PRY', :display => true)
    GeoCountry.create(:name => 'Peru', :iso_code_2 => 'PE', :iso_code_3 => 'PER', :display => true)
    GeoCountry.create(:name => 'Philippines', :iso_code_2 => 'PH', :iso_code_3 => 'PHL', :display => true)
    GeoCountry.create(:name => 'Pitcairn', :iso_code_2 => 'PN', :iso_code_3 => 'PCN', :display => true)
    GeoCountry.create(:name => 'Poland', :iso_code_2 => 'PL', :iso_code_3 => 'POL', :display => true)
    GeoCountry.create(:name => 'Portugal', :iso_code_2 => 'PT', :iso_code_3 => 'PRT', :display => true)
    GeoCountry.create(:name => 'Puerto Rico', :iso_code_2 => 'PR', :iso_code_3 => 'PRI', :display => true)
    GeoCountry.create(:name => 'Qatar', :iso_code_2 => 'QA', :iso_code_3 => 'QAT', :display => true)
    GeoCountry.create(:name => 'Reunion', :iso_code_2 => 'RE', :iso_code_3 => 'REU', :display => true)
    GeoCountry.create(:name => 'Romania', :iso_code_2 => 'RO', :iso_code_3 => 'ROM', :display => true)
    GeoCountry.create(:name => 'Russian Federation', :iso_code_2 => 'RU', :iso_code_3 => 'RUS', :display => true)
    GeoCountry.create(:name => 'Rwanda', :iso_code_2 => 'RW', :iso_code_3 => 'RWA', :display => true)
    GeoCountry.create(:name => 'Saint Kitts and Nevis', :iso_code_2 => 'KN', :iso_code_3 => 'KNA', :display => true)
    GeoCountry.create(:name => 'Saint Lucia', :iso_code_2 => 'LC', :iso_code_3 => 'LCA', :display => true)
    GeoCountry.create(:name => 'Saint Vincent and the Grenadines', :iso_code_2 => 'VC', :iso_code_3 => 'VCT', :display => true)
    GeoCountry.create(:name => 'Samoa', :iso_code_2 => 'WS', :iso_code_3 => 'WSM', :display => true)
    GeoCountry.create(:name => 'San Marino', :iso_code_2 => 'SM', :iso_code_3 => 'SMR', :display => true)
    GeoCountry.create(:name => 'Sao Tome and Principe', :iso_code_2 => 'ST', :iso_code_3 => 'STP', :display => true)
    GeoCountry.create(:name => 'Saudi Arabia', :iso_code_2 => 'SA', :iso_code_3 => 'SAU', :display => true)
    GeoCountry.create(:name => 'Senegal', :iso_code_2 => 'SN', :iso_code_3 => 'SEN', :display => true)
    GeoCountry.create(:name => 'Seychelles', :iso_code_2 => 'SC', :iso_code_3 => 'SYC', :display => true)
    GeoCountry.create(:name => 'Sierra Leone', :iso_code_2 => 'SL', :iso_code_3 => 'SLE', :display => true)
    GeoCountry.create(:name => 'Singapore', :iso_code_2 => 'SG', :iso_code_3 => 'SGP', :display => true)
    GeoCountry.create(:name => 'Slovakia (Slovak Republic)', :iso_code_2 => 'SK', :iso_code_3 => 'SVK', :display => true)
    GeoCountry.create(:name => 'Slovenia', :iso_code_2 => 'SI', :iso_code_3 => 'SVN', :display => true)
    GeoCountry.create(:name => 'Solomon Islands', :iso_code_2 => 'SB', :iso_code_3 => 'SLB', :display => true)
    GeoCountry.create(:name => 'Somalia', :iso_code_2 => 'SO', :iso_code_3 => 'SOM', :display => true)
    GeoCountry.create(:name => 'South Africa', :iso_code_2 => 'ZA', :iso_code_3 => 'ZAF', :display => true)
    GeoCountry.create(:name => 'South Georgia and the South Sandwich Islands', :iso_code_2 => 'GS', :iso_code_3 => 'SGS', :display => true)
    GeoCountry.create(:name => 'Spain', :iso_code_2 => 'ES', :iso_code_3 => 'ESP', :display => true)
    GeoCountry.create(:name => 'Sri Lanka', :iso_code_2 => 'LK', :iso_code_3 => 'LKA', :display => true)
    GeoCountry.create(:name => 'St. Helena', :iso_code_2 => 'SH', :iso_code_3 => 'SHN', :display => true)
    GeoCountry.create(:name => 'St. Pierre and Miquelon', :iso_code_2 => 'PM', :iso_code_3 => 'SPM', :display => true)
    GeoCountry.create(:name => 'Sudan', :iso_code_2 => 'SD', :iso_code_3 => 'SDN', :display => true)
    GeoCountry.create(:name => 'Suriname', :iso_code_2 => 'SR', :iso_code_3 => 'SUR', :display => true)
    GeoCountry.create(:name => 'Svalbard and Jan Mayen Islands', :iso_code_2 => 'SJ', :iso_code_3 => 'SJM', :display => true)
    GeoCountry.create(:name => 'Swaziland', :iso_code_2 => 'SZ', :iso_code_3 => 'SWZ', :display => true)
    GeoCountry.create(:name => 'Sweden', :iso_code_2 => 'SE', :iso_code_3 => 'SWE', :display => true)
    GeoCountry.create(:name => 'Switzerland', :iso_code_2 => 'CH', :iso_code_3 => 'CHE', :display => true)
    GeoCountry.create(:name => 'Syrian Arab Republic', :iso_code_2 => 'SY', :iso_code_3 => 'SYR', :display => true)
    GeoCountry.create(:name => 'Taiwan', :iso_code_2 => 'TW', :iso_code_3 => 'TWN', :display => true)
    GeoCountry.create(:name => 'Tajikistan', :iso_code_2 => 'TJ', :iso_code_3 => 'TJK', :display => true)
    GeoCountry.create(:name => 'Tanzania, United Republic of', :iso_code_2 => 'TZ', :iso_code_3 => 'TZA', :display => true)
    GeoCountry.create(:name => 'Thailand', :iso_code_2 => 'TH', :iso_code_3 => 'THA', :display => true)
    GeoCountry.create(:name => 'Togo', :iso_code_2 => 'TG', :iso_code_3 => 'TGO', :display => true)
    GeoCountry.create(:name => 'Tokelau', :iso_code_2 => 'TK', :iso_code_3 => 'TKL', :display => true)
    GeoCountry.create(:name => 'Tonga', :iso_code_2 => 'TO', :iso_code_3 => 'TON', :display => true)
    GeoCountry.create(:name => 'Trinidad and Tobago', :iso_code_2 => 'TT', :iso_code_3 => 'TTO', :display => true)
    GeoCountry.create(:name => 'Tunisia', :iso_code_2 => 'TN', :iso_code_3 => 'TUN', :display => true)
    GeoCountry.create(:name => 'Turkey', :iso_code_2 => 'TR', :iso_code_3 => 'TUR', :display => true)
    GeoCountry.create(:name => 'Turkmenistan', :iso_code_2 => 'TM', :iso_code_3 => 'TKM', :display => true)
    GeoCountry.create(:name => 'Turks and Caicos Islands', :iso_code_2 => 'TC', :iso_code_3 => 'TCA', :display => true)
    GeoCountry.create(:name => 'Tuvalu', :iso_code_2 => 'TV', :iso_code_3 => 'TUV', :display => true)
    GeoCountry.create(:name => 'Uganda', :iso_code_2 => 'UG', :iso_code_3 => 'UGA', :display => true)
    GeoCountry.create(:name => 'Ukraine', :iso_code_2 => 'UA', :iso_code_3 => 'UKR', :display => true)
    GeoCountry.create(:name => 'United Arab Emirates', :iso_code_2 => 'AE', :iso_code_3 => 'ARE', :display => true)
    GeoCountry.create(:name => 'United Kingdom', :iso_code_2 => 'GB', :iso_code_3 => 'GBR', :display => true)
    GeoCountry.create(:name => 'United States', :iso_code_2 => 'US', :iso_code_3 => 'USA', :display => true)
    GeoCountry.create(:name => 'United States Minor Outlying Islands', :iso_code_2 => 'UM', :iso_code_3 => 'UMI', :display => true)
    GeoCountry.create(:name => 'Uruguay', :iso_code_2 => 'UY', :iso_code_3 => 'URY', :display => true)
    GeoCountry.create(:name => 'Uzbekistan', :iso_code_2 => 'UZ', :iso_code_3 => 'UZB', :display => true)
    GeoCountry.create(:name => 'Vanuatu', :iso_code_2 => 'VU', :iso_code_3 => 'VUT', :display => true)
    GeoCountry.create(:name => 'Vatican City State', :iso_code_2 => 'VA', :iso_code_3 => 'VAT', :display => true)
    GeoCountry.create(:name => 'Venezuela', :iso_code_2 => 'VE', :iso_code_3 => 'VEN', :display => true)
    GeoCountry.create(:name => 'Viet Nam', :iso_code_2 => 'VN', :iso_code_3 => 'VNM', :display => true)
    GeoCountry.create(:name => 'Virgin Islands (British)', :iso_code_2 => 'VG', :iso_code_3 => 'VGB', :display => true)
    GeoCountry.create(:name => 'Virgin Islands (U.S.)', :iso_code_2 => 'VI', :iso_code_3 => 'VIR', :display => true)
    GeoCountry.create(:name => 'Wallis and Futuna Islands', :iso_code_2 => 'WF', :iso_code_3 => 'WLF', :display => true)
    GeoCountry.create(:name => 'Western Sahara', :iso_code_2 => 'EH', :iso_code_3 => 'ESH', :display => true)
    GeoCountry.create(:name => 'Yemen', :iso_code_2 => 'YE', :iso_code_3 => 'YEM', :display => true)
    GeoCountry.create(:name => 'Yugoslavia', :iso_code_2 => 'YU', :iso_code_3 => 'YUG', :display => true)
    GeoCountry.create(:name => 'Zaire', :iso_code_2 => 'ZR', :iso_code_3 => 'ZAR', :display => true)
    GeoCountry.create(:name => 'Zambia', :iso_code_2 => 'ZM', :iso_code_3 => 'ZMB', :display => true)
    GeoCountry.create(:name => 'Zimbabwe', :iso_code_2 => 'ZW', :iso_code_3 => 'ZWE', :display => true)

    create_table :geo_zones do |t|
      t.column :geo_country_id, :integer
      t.column :zone_code, :string, :default => 2
      t.column :zone_name, :string
      t.column :created_at, :datetime
    end

    cntry = GeoCountry.find_by_name('United States')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AL', :zone_name => 'Alabama')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AK', :zone_name => 'Alaska')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AS', :zone_name => 'American Samoa')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AZ', :zone_name => 'Arizona')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AR', :zone_name => 'Arkansas')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AF', :zone_name => 'Armed Forces')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'CA', :zone_name => 'California')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'CO', :zone_name => 'Colorado')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'CT', :zone_name => 'Connecticut')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'DE', :zone_name => 'Delaware')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'DC', :zone_name => 'District of Columbia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'FM', :zone_name => 'Federated States Of Micronesia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'FL', :zone_name => 'Florida')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'GA', :zone_name => 'Georgia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'GU', :zone_name => 'Guam')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'HI', :zone_name => 'Hawaii')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'ID', :zone_name => 'Idaho')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'IL', :zone_name => 'Illinois')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'IN', :zone_name => 'Indiana')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'IA', :zone_name => 'Iowa')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'KS', :zone_name => 'Kansas')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'KY', :zone_name => 'Kentucky')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'LA', :zone_name => 'Louisiana')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'ME', :zone_name => 'Maine')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MH', :zone_name => 'Marshall Islands')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MD', :zone_name => 'Maryland')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MA', :zone_name => 'Massachusetts')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MI', :zone_name => 'Michigan')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MN', :zone_name => 'Minnesota')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MS', :zone_name => 'Mississippi')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MO', :zone_name => 'Missouri')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MT', :zone_name => 'Montana')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NE', :zone_name => 'Nebraska')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NV', :zone_name => 'Nevada')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NH', :zone_name => 'New Hampshire')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NJ', :zone_name => 'New Jersey')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NM', :zone_name => 'New Mexico')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NY', :zone_name => 'New York')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NC', :zone_name => 'North Carolina')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'ND', :zone_name => 'North Dakota')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MP', :zone_name => 'Northern Mariana Islands')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'OH', :zone_name => 'Ohio')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'OK', :zone_name => 'Oklahoma')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'OR', :zone_name => 'Oregon')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'PW', :zone_name => 'Palau')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'PA', :zone_name => 'Pennsylvania')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'PR', :zone_name => 'Puerto Rico')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'RI', :zone_name => 'Rhode Island')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SC', :zone_name => 'South Carolina')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SD', :zone_name => 'South Dakota')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'TN', :zone_name => 'Tennessee')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'TX', :zone_name => 'Texas')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'UT', :zone_name => 'Utah')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'VT', :zone_name => 'Vermont')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'VI', :zone_name => 'Virgin Islands')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'VA', :zone_name => 'Virginia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'WA', :zone_name => 'Washington')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'WV', :zone_name => 'West Virginia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'WI', :zone_name => 'Wisconsin')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'WY', :zone_name => 'Wyoming')

    cntry = GeoCountry.find_by_name('Canada')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AB', :zone_name => 'Alberta')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BC', :zone_name => 'British Columbia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MB', :zone_name => 'Manitoba')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NF', :zone_name => 'Newfoundland')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NB', :zone_name => 'New Brunswick')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NS', :zone_name => 'Nova Scotia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NT', :zone_name => 'Northwest Territories')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NU', :zone_name => 'Nunavut')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'ON', :zone_name => 'Ontario')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'PE', :zone_name => 'Prince Edward Island')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'QC', :zone_name => 'Quebec')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SK', :zone_name => 'Saskatchewan')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'YT', :zone_name => 'Yukon Territory')

    cntry = GeoCountry.find_by_name('Germany')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NDS', :zone_name => 'Niedersachsen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BAW', :zone_name => 'Baden-Württemberg')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BAY', :zone_name => 'Bayern')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BER', :zone_name => 'Berlin')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BRG', :zone_name => 'Brandenburg')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BRE', :zone_name => 'Bremen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'HAM', :zone_name => 'Hamburg')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'HES', :zone_name => 'Hessen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'MEC', :zone_name => 'Mecklenburg-Vorpommern')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NRW', :zone_name => 'Nordrhein-Westfalen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'RHE', :zone_name => 'Rheinland-Pfalz')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SAR', :zone_name => 'Saarland')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SAS', :zone_name => 'Sachsen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SAC', :zone_name => 'Sachsen-Anhalt')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SCN', :zone_name => 'Schleswig-Holstein')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'THE', :zone_name => 'Thüringen')

    cntry = GeoCountry.find_by_name('Austria')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'WI', :zone_name => 'Wien')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NO', :zone_name => 'Niederösterreich')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'OO', :zone_name => 'Oberösterreich')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SB', :zone_name => 'Salzburg')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'KN', :zone_name => 'Kärnten')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'ST', :zone_name => 'Steiermark')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'TI', :zone_name => 'Tirol')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BL', :zone_name => 'Burgenland')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'VB', :zone_name => 'Voralberg')

    cntry = GeoCountry.find_by_name('Switzerland')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AG', :zone_name => 'Aargau')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AI', :zone_name => 'Appenzell Innerrhoden')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'AR', :zone_name => 'Appenzell Ausserrhoden')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BE', :zone_name => 'Bern')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BL', :zone_name => 'Basel-Landschaft')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'BS', :zone_name => 'Basel-Stadt')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'FR', :zone_name => 'Freiburg')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'GE', :zone_name => 'Genf')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'GL', :zone_name => 'Glarus')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'JU', :zone_name => 'Graubünden')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'JU', :zone_name => 'Jura')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'LU', :zone_name => 'Luzern')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NE', :zone_name => 'Neuenburg')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'NW', :zone_name => 'Nidwalden')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'OW', :zone_name => 'Obwalden')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SG', :zone_name => 'St. Gallen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SH', :zone_name => 'Schaffhausen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SO', :zone_name => 'Solothurn')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'SZ', :zone_name => 'Schwyz')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'TG', :zone_name => 'Thurgau')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'TI', :zone_name => 'Tessin')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'UR', :zone_name => 'Uri')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'VD', :zone_name => 'Waadt')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'VS', :zone_name => 'Wallis')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'ZG', :zone_name => 'Zug')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'ZH', :zone_name => 'Zürich')

    cntry = GeoCountry.find_by_name('Spain')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'A Coruña', :zone_name => 'A Coruña')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Alava', :zone_name => 'Alava')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Albacete', :zone_name => 'Albacete')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Alicante', :zone_name => 'Alicante')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Almeria', :zone_name => 'Almeria')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Asturias', :zone_name => 'Asturias')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Avila', :zone_name => 'Avila')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Badajoz', :zone_name => 'Badajoz')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Baleares', :zone_name => 'Baleares')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Barcelona', :zone_name => 'Barcelona')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Burgos', :zone_name => 'Burgos')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Caceres', :zone_name => 'Caceres')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Cadiz', :zone_name => 'Cadiz')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Cantabria', :zone_name => 'Cantabria')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Castellon', :zone_name => 'Castellon')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Ceuta', :zone_name => 'Ceuta')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Ciudad Real', :zone_name => 'Ciudad Real')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Cordoba', :zone_name => 'Cordoba')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Cuenca', :zone_name => 'Cuenca')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Girona', :zone_name => 'Girona')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Granada', :zone_name => 'Granada')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Guadalajara', :zone_name => 'Guadalajara')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Guipuzcoa', :zone_name => 'Guipuzcoa')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Huelva', :zone_name => 'Huelva')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Huesca', :zone_name => 'Huesca')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Jaen', :zone_name => 'Jaen')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'La Rioja', :zone_name => 'La Rioja')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Las Palmas', :zone_name => 'Las Palmas')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Leon', :zone_name => 'Leon')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Lleida', :zone_name => 'Lleida')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Lugo', :zone_name => 'Lugo')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Madrid', :zone_name => 'Madrid')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Malaga', :zone_name => 'Malaga')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Melilla', :zone_name => 'Melilla')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Murcia', :zone_name => 'Murcia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Navarra', :zone_name => 'Navarra')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Ourense', :zone_name => 'Ourense')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Palencia', :zone_name => 'Palencia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Pontevedra', :zone_name => 'Pontevedra')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Salamanca', :zone_name => 'Salamanca')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Santa Cruz de Tenerife', :zone_name => 'Santa Cruz de Tenerife')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Segovia', :zone_name => 'Segovia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Sevilla', :zone_name => 'Sevilla')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Soria', :zone_name => 'Soria')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Tarragona', :zone_name => 'Tarragona')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Teruel', :zone_name => 'Teruel')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Toledo', :zone_name => 'Toledo')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Valencia', :zone_name => 'Valencia')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Valladolid', :zone_name => 'Valladolid')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Vizcaya', :zone_name => 'Vizcaya')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Zamora', :zone_name => 'Zamora')
    GeoZone.create(:geo_country_id => cntry.id, :zone_code => 'Zaragoza', :zone_name => 'Zaragoza')

    add_column :postal_addresses, :geo_country_id, :integer
    add_column :postal_addresses, :geo_zone_id, :integer
  end
#BN
  def self.down
    drop_table :geo_countries
    drop_table :geo_zones
    remove_column :postal_addresses, :geo_country_id
    remove_column :postal_addresses, :geo_zone_id
  end
end
