source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3'

gem 'jquery-rails'
# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development, :test do
  gem 'rspec-rails', '~> 2.5'
end

gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'