source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '~> 1.3.4'
gem 'jquery-rails', '1.0.13'
gem 'activemerchant', '1.17.0'
gem "aasm", "2.3.1"

# Compass AE engines
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'
gem 'erp_orders', :path => '../erp_orders'

group :development, :test do
  gem 'rspec-rails', '2.5'
end



