source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '1.3.4'
gem 'jquery-rails', '1.0.13'

# Compass AE engines
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'
gem 'erp_app', :path => '../erp_app'

group :development, :test do
  gem 'cucumber-rails', "~> 1.1.1"
  gem 'database_cleaner'
  gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
  gem 'factory_girl_rails', '1.2.0'
  gem 'rspec-rails', '~> 2.7'
  gem 'watchr'
  gem 'spork', '~> 0.9.0.rc'
  gem 'simplecov', '>= 0.5.4'
end

