source "http://rubygems.org"

gem 'rails', '3.1'
gem 'sqlite3', '~> 1.3.4'
gem 'jquery-rails', '1.0.13'
gem 'will_paginate', '3.0.0'

# Compass AE engines
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'

group :development, :test do
  gem 'rspec-rails', '2.5'
  gem 'factory_girl_rails', '1.2.0'
end



