require 'erp_products/extensions/active_record/acts_as_product_instance'
require 'erp_products/extensions/active_record/acts_as_product_offer'
require 'erp_products/extensions/active_record/acts_as_product_type'